name: Docker Image CI

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t luna28kenya412/my-htmlqa1-app .
      - name: Publish image to Docker Hub
        run: docker push luna28kenya412/my-htmlqa1-app:latest

  deploy-to-ec2-instance1:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2 (Instance 1)
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST2 }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY2 }}
          script: |
            docker pull luna28kenya412/my-htmlqa1-app:latest
            docker stop my_container_instance1 || true
            docker rm my_container_instance1 || true
            docker run -d --name my_container_instance1 -p 8082:80 luna28kenya412/my-htmlqa1-app:latest

  deploy-to-ec2-instance2:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2 (Instance 2)
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST3 }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY3 }}
          script: |
            docker pull luna28kenya412/my-htmlqa1-app:latest
            docker stop my_container_instance2 || true
            docker rm my_container_instance2 || true
            docker run -d --name my_container_instance2 -p 8083:80 luna28kenya412/my-htmlqa1-app:latest

  deploy-to-ec2-instance3:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2 (Instance 3)
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST4 }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY4 }}
          script: |
            docker pull luna28kenya412/my-htmlqa1-app:latest
            docker stop my_container_instance3 || true
            docker rm my_container_instance3 || true
            docker run -d --name my_container_instance3 -p 8084:80 luna28kenya412/my-htmlqa1-app:latest

  deploy-to-ec2-instance4:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2 (Instance 4)
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST5 }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY5 }}
          script: |
            docker pull luna28kenya412/my-htmlqa1-app:latest
            docker stop my_container_instance4 || true
            docker rm my_container_instance4 || true
            docker run -d --name my_container_instance4 -p 8085:80 luna28kenya412/my-htmlqa1-app:latest
